### PR TITLE
Fixes Errors

### PR DESCRIPTION
**Pull request by Savnith**
Small Plugin Errors fixed :D

### CODE REVIEW

**Comment by robingall2910** [comment]
can't merge without you signing the agreement

**Comment by CreeperSeth** [comment]
the one thing I missed... god damnit

**Comment by OxLemonxO** [comment]
yes you can @robingall2910?

**Comment by OxLemonxO** [comment]
Merged.

**Comment by OutOfYourMind** [comment]
@OxLemonxO he didn't sign it

**Pull request merged**
